apiVersion: v1
kind: Secret
metadata:
  name: "${SECRET_NAME}"
  annotations:
    kubernetes.io/service-account.name: "{ksa-name}"
type: kubernetes.io/service-account-token

#until [[ $(kubectl get -o=jsonpath="{.data.token}" "secret/${SECRET_NAME}") ]]; do
#  echo "waiting for token…" >&2;
#  sleep 1;
#done